name: Publish Docs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  docs-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install
        run: npm ci

      - name: Publish
        run: npm run docs:build

      - name: Publish documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          dir: ./packages/lib/dist
          branch: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}
